services:
  - type: web
    name: my-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    build:
      cacheDirs:
        - node_modules
        - .next/cache
